services:
  - name: tooltip-api
    type: web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:5000 server:app
    envVars:
      - key: DATABASE_URL
        value: sqlite:///bible_tracker.db
